export const NORMALIZATION_MAP = {
  致郁: "黑暗",
  阴暗: "黑暗",
  压抑: "黑暗",
  残酷: "黑暗",
  悲剧: "黑暗",
  温馨: "治愈",
  温暖: "治愈",
  感动: "治愈",
  催泪: "治愈",
  青春: "成长",
  成长系: "成长",
  恋爱: "情感",
  爱情: "情感",
  战斗: "热血",
  冒险: "幻想",
  异世界: "幻想",
  奇幻: "幻想",
  科幻: "幻想",
  推理: "理性",
  悬疑: "悬疑",
  群像: "关系",
  日常系: "日常",
  校园生活: "校园",
  治愈系: "治愈",
  友情: "关系",
  家庭: "关系",
  心理: "代入",
  现实向: "现实",
  音乐: "音乐",
  偶像: "音乐",
  舞台: "音乐",
  社会: "现实",
  人性: "代入",
  命运: "代入",
  战争: "黑暗",
  末世: "黑暗",
  超能力: "刺激",
  赛博朋克: "幻想",
  机器人: "幻想",
  百合: "情感",
  少女: "关系",
  男性主角: "个人",
  女性主角: "关系",
  机战: "热血",
  宗教: "幻想",
  意识流: "叙事",
  神棍: "幻想",
  穿越: "幻想",
  智斗: "叙事",
  犯罪: "黑暗",
  古代: "幻想",
  历史: "现实",
  耽美: "情感",
  BL: "情感",
  黑帮: "黑暗",
  心理学: "代入",
  剧情: "叙事",
  喜剧: "幽默",
  搞笑: "幽默",
};

/**
 * 14 维偏好空间（展示均为 2 字）
 * 治愈/黑暗/热血/悬疑/幻想/现实/日常/感性/关系/成长/理性/叙事/幽默/音乐
 */
export const DIMENSION_KEYS = [
  "healing",
  "dark",
  "passion",
  "suspense",
  "fantasy",
  "realism",
  "daily",
  "emotion",
  "bond",
  "growth",
  "logic",
  "narrative",
  "humor",
  "music",
];

export const DIMENSION_LABELS = {
  healing: "治愈",
  dark: "黑暗",
  passion: "热血",
  suspense: "悬疑",
  fantasy: "幻想",
  realism: "现实",
  daily: "日常",
  emotion: "感性",
  bond: "关系",
  growth: "成长",
  logic: "理性",
  narrative: "叙事",
  humor: "幽默",
  music: "音乐",
};

const LEGACY_DIMENSION_ALIASES = {
  fantasy_immersion: "fantasy",
  escape: "fantasy",
  projection: "fantasy",
  stimulation: "suspense",
  analytical: "logic",
  plot_complex: "narrative",
  emotional: "emotion",
  relationship_focus: "bond",
  individual_focus: "growth",
};

export function resolveDimensionKey(dimension) {
  return LEGACY_DIMENSION_ALIASES[dimension] || dimension;
}

export const TAG_DIMENSION_MAP = {
  治愈: { healing: 1.4, emotion: 0.5, bond: 0.4 },
  黑暗: { dark: 1.4, suspense: 0.4, emotion: 0.3 },
  热血: { passion: 1.5, suspense: 0.5 },
  幻想: { fantasy: 1.5 },
  现实: { realism: 1.4, growth: 0.4 },
  代入: { fantasy: 1.2, emotion: 0.5, growth: 0.5 },
  刺激: { suspense: 1.2, passion: 0.7 },
  理性: { logic: 1.4, narrative: 0.6 },
  情感: { emotion: 1.4, bond: 0.8 },
  关系: { bond: 1.5, healing: 0.4 },
  个人: { growth: 1.3, logic: 0.3 },
  复杂剧情: { narrative: 1.5, logic: 0.7 },
  叙事: { narrative: 1.5, logic: 0.5 },
  日常: { daily: 1.5, healing: 0.6 },
  成长: { growth: 1.4, realism: 0.5, healing: 0.4 },
  校园: { daily: 0.7, realism: 0.6, bond: 0.5, growth: 0.5 },
  战争: { dark: 0.8, passion: 0.7, narrative: 0.4 },
  家庭: { bond: 1.0, healing: 1.0, emotion: 0.5 },
  友情: { bond: 1.1, healing: 0.6 },
  恋爱: { emotion: 1.2, bond: 1.0 },
  冒险: { fantasy: 1.0, passion: 0.6, suspense: 0.5 },
  推理: { logic: 1.3, narrative: 1.0, suspense: 0.5 },
  悬疑: { suspense: 1.2, narrative: 0.9, dark: 0.5 },
  搞笑: { humor: 1.4, daily: 0.6 },
  幽默: { humor: 1.5, daily: 0.5 },
  喜剧: { humor: 1.3, daily: 0.7, healing: 0.3 },
  命运: { emotion: 0.8, fantasy: 0.6, dark: 0.3 },
  牺牲: { dark: 0.8, emotion: 0.8, bond: 0.4 },
  孤独: { growth: 1.0, dark: 0.5, emotion: 0.5 },
  自由: { growth: 0.8, fantasy: 0.6, passion: 0.4 },
  音乐: { music: 1.5, emotion: 0.6 },
  偶像: { music: 1.0, bond: 0.9, emotion: 0.7 },
  舞台: { music: 0.9, emotion: 0.7, passion: 0.4 },
  社会: { realism: 1.0, logic: 0.6, dark: 0.3 },
  人性: { emotion: 0.7, logic: 0.5, growth: 0.5 },
  末世: { dark: 1.0, fantasy: 0.4, suspense: 0.5 },
  超能力: { fantasy: 0.8, suspense: 0.6, passion: 0.4 },
  机器人: { fantasy: 0.7, logic: 0.6, realism: 0.3 },
  百合: { emotion: 1.0, bond: 1.0 },
  少女: { bond: 0.7, emotion: 0.6, daily: 0.3 },
  魔法: { fantasy: 1.0, emotion: 0.3 },
  儿童: { healing: 0.9, daily: 0.7, fantasy: 0.5, bond: 0.4 },
  哲学: { logic: 0.8, growth: 0.5, realism: 0.4 },
  亲情: { bond: 1.0, healing: 0.9, emotion: 0.7 },
  职场: { realism: 0.9, growth: 0.6, daily: 0.4 },
  体操: { passion: 0.7, growth: 0.8, emotion: 0.5 },
  神魔: { fantasy: 1.0, dark: 0.5, suspense: 0.3 },
  架空: { fantasy: 1.0, narrative: 0.5 },
  旅行: { daily: 0.6, healing: 0.6, growth: 0.5, fantasy: 0.3 },
  妖怪: { fantasy: 0.7, dark: 0.4, suspense: 0.3 },
  女性: { bond: 0.6, emotion: 0.7, growth: 0.4 },
  男性: { passion: 0.6, growth: 0.5, suspense: 0.3 },
};

export const PERSONALITY_TYPES = [
  {
    name: "治愈型投射者",
    dimensions: { healing: 1, fantasy: 0.85 },
    traits: ["治愈倾向", "高代入感", "情绪修复"],
  },
  {
    name: "深渊观察者",
    dimensions: { dark: 1, suspense: -0.3 },
    traits: ["黑暗审美", "冷静旁观", "低悬疑耐受"],
  },
  {
    name: "热血行动派",
    dimensions: { passion: 1, suspense: 0.75 },
    traits: ["行动驱动", "追求燃点", "冲劲强"],
  },
  {
    name: "幻想逃逸者",
    dimensions: { fantasy: 1 },
    traits: ["幻想偏好", "抽离现实", "沉浸世界观"],
  },
  {
    name: "情感依赖者",
    dimensions: { healing: 1, bond: 1 },
    traits: ["重视羁绊", "情感补偿", "关系敏感"],
  },
  {
    name: "理性解构者",
    dimensions: { logic: 1, narrative: 1 },
    traits: ["结构控", "逻辑偏好", "喜欢拆解设定"],
  },
  {
    name: "戏剧沉浸者",
    dimensions: { emotion: 1, dark: 1 },
    traits: ["戏剧浓度高", "情绪投入深", "接受沉重表达"],
  },
  {
    name: "日常享乐者",
    dimensions: { daily: 1, healing: 1 },
    traits: ["日常偏好", "轻松陪伴", "舒缓体验"],
  },
  {
    name: "冲突追求者",
    dimensions: { suspense: 1, dark: 1 },
    traits: ["冲突导向", "刺激阈值高", "偏好高压叙事"],
  },
  {
    name: "浪漫理想家",
    dimensions: { fantasy: 0.95, emotion: 1 },
    traits: ["浪漫滤镜", "理想化情感", "重氛围"],
  },
  {
    name: "自我投射者",
    dimensions: { fantasy: 0.75, realism: 1, growth: 0.8 },
    traits: ["现实映照", "角色共鸣", "自我代换"],
  },
  {
    name: "平衡探索者",
    dimensions: {},
    traits: ["口味均衡", "尝试面广", "适应多元类型"],
  },
];
