export const NORMALIZATION_MAP = {
  致郁: "黑暗",
  阴暗: "黑暗",
  压抑: "黑暗",
  残酷: "黑暗",
  悲剧: "黑暗",
  温馨: "治愈",
  温暖: "治愈",
  感动: "治愈",
  催泪: "治愈",
  青春: "成长",
  成长系: "成长",
  恋爱: "情感",
  爱情: "情感",
  战斗: "热血",
  冒险: "幻想",
  异世界: "幻想",
  奇幻: "幻想",
  科幻: "幻想",
  推理: "理性",
  悬疑: "复杂剧情",
  群像: "关系",
  日常系: "日常",
  校园生活: "校园",
  治愈系: "治愈",
  友情: "关系",
  家庭: "关系",
  心理: "代入",
  现实向: "现实",
  音乐: "情感",
  偶像: "关系",
  舞台: "情感",
  社会: "现实",
  人性: "代入",
  命运: "代入",
  战争: "黑暗",
  末世: "黑暗",
  超能力: "刺激",
  赛博朋克: "幻想",
  机器人: "幻想",
  百合: "情感",
  少女: "关系",
  男性主角: "个人",
  女性主角: "关系",
  机战: "热血",
  宗教: "幻想",
  意识流: "复杂剧情",
  神棍: "幻想",
  穿越: "幻想",
  智斗: "复杂剧情",
  犯罪: "黑暗",
  古代: "幻想",
  历史: "现实",
  耽美: "情感",
  BL: "情感",
  黑帮: "黑暗",
  心理学: "代入",
  剧情: "复杂剧情",
};

export const TAG_DIMENSION_MAP = {
  治愈: { healing: 1.4, emotional: 0.5, relationship_focus: 0.5 },
  黑暗: { dark: 1.4, stimulation: 0.5, emotional: 0.4 },
  热血: { passion: 1.5, stimulation: 1.1 },
  幻想: { fantasy: 1.5, escape: 0.8 },
  现实: { realism: 1.4, projection: 0.6 },
  代入: { projection: 1.5, emotional: 0.4 },
  刺激: { stimulation: 1.5, passion: 0.6 },
  理性: { analytical: 1.4, plot_complex: 0.7 },
  情感: { emotional: 1.4, relationship_focus: 0.8 },
  关系: { relationship_focus: 1.5, healing: 0.4 },
  个人: { individual_focus: 1.4, analytical: 0.4 },
  复杂剧情: { plot_complex: 1.5, analytical: 0.8 },
  日常: { daily: 1.5, healing: 0.8 },
  成长: { projection: 0.8, realism: 0.6, healing: 0.5 },
  校园: { daily: 0.8, realism: 0.8, relationship_focus: 0.5 },
  战争: { dark: 0.8, stimulation: 1.0, plot_complex: 0.4 },
  家庭: { relationship_focus: 1.0, healing: 1.0, projection: 0.4 },
  友情: { relationship_focus: 1.1, healing: 0.7 },
  恋爱: { emotional: 1.2, relationship_focus: 1.0 },
  冒险: { fantasy: 1.0, stimulation: 1.0, escape: 0.5 },
  推理: { analytical: 1.2, plot_complex: 1.1 },
  悬疑: { dark: 0.7, plot_complex: 1.2, stimulation: 0.8 },
  搞笑: { daily: 0.8, healing: 0.6 },
  命运: { projection: 0.8, emotional: 0.8, dark: 0.3 },
  牺牲: { dark: 0.8, emotional: 0.8, relationship_focus: 0.3 },
  孤独: { individual_focus: 1.0, dark: 0.6, projection: 0.6 },
  自由: { individual_focus: 0.9, fantasy: 0.7, stimulation: 0.4 },
  音乐: { emotional: 1.0, relationship_focus: 0.6, daily: 0.5 },
  偶像: { relationship_focus: 0.9, emotional: 0.9, daily: 0.4 },
  舞台: { emotional: 0.8, stimulation: 0.6, projection: 0.4 },
  社会: { realism: 1.0, analytical: 0.7, dark: 0.3 },
  人性: { projection: 0.8, analytical: 0.6, emotional: 0.5 },
  末世: { dark: 1.0, fantasy: 0.5, stimulation: 0.5 },
  超能力: { fantasy: 0.8, stimulation: 0.9, projection: 0.3 },
  机器人: { fantasy: 0.8, analytical: 0.7, realism: 0.3 },
  百合: { emotional: 1.0, relationship_focus: 1.0 },
  少女: { relationship_focus: 0.8, emotional: 0.6, daily: 0.3 },
};

export const PERSONALITY_TYPES = [
  {
    name: "治愈型投射者",
    dimensions: { healing: 1, projection: 1 },
    traits: ["治愈倾向", "高代入感", "情绪修复"],
  },
  {
    name: "深渊观察者",
    dimensions: { dark: 1, stimulation: -0.4 },
    traits: ["黑暗审美", "冷静旁观", "低刺激耐受"],
  },
  {
    name: "热血行动派",
    dimensions: { passion: 1, stimulation: 1 },
    traits: ["行动驱动", "追求燃点", "冲劲强"],
  },
  {
    name: "幻想逃逸者",
    dimensions: { fantasy: 1, escape: 1 },
    traits: ["幻想偏好", "抽离现实", "沉浸世界观"],
  },
  {
    name: "情感依赖者",
    dimensions: { healing: 1, relationship_focus: 1 },
    traits: ["重视羁绊", "情感补偿", "关系敏感"],
  },
  {
    name: "理性解构者",
    dimensions: { analytical: 1, plot_complex: 1 },
    traits: ["结构控", "逻辑偏好", "喜欢拆解设定"],
  },
  {
    name: "戏剧沉浸者",
    dimensions: { emotional: 1, dark: 1 },
    traits: ["戏剧浓度高", "情绪投入深", "接受沉重表达"],
  },
  {
    name: "日常享乐者",
    dimensions: { daily: 1, healing: 1 },
    traits: ["日常偏好", "轻松陪伴", "舒缓体验"],
  },
  {
    name: "冲突追求者",
    dimensions: { stimulation: 1, dark: 1 },
    traits: ["冲突导向", "刺激阈值高", "偏好高压叙事"],
  },
  {
    name: "浪漫理想家",
    dimensions: { fantasy: 1, emotional: 1 },
    traits: ["浪漫滤镜", "理想化情感", "重氛围"],
  },
  {
    name: "自我投射者",
    dimensions: { projection: 1, realism: 1 },
    traits: ["现实映照", "角色共鸣", "自我代换"],
  },
  {
    name: "平衡探索者",
    dimensions: {},
    traits: ["口味均衡", "尝试面广", "适应多元类型"],
  },
];

export const DIMENSION_KEYS = [
  "healing",
  "dark",
  "passion",
  "fantasy",
  "realism",
  "projection",
  "escape",
  "stimulation",
  "analytical",
  "emotional",
  "relationship_focus",
  "individual_focus",
  "plot_complex",
  "daily",
];
